Repository WildCodeSchool/orleans-php-2003-project-anc, pull requests merged in 2020-04, with the labels that each got.

#2 first commit
  public/assets/css/style.css
Labels: corrections done

#9 S01 us01 visiteur home page header
  public/assets/css/homePage/header.css
  public/assets/css/style.css
  public/assets/images/anniversary_medal.png
  public/assets/images/bg_header.jpeg
  public/assets/images/favicon.png
  public/assets/images/favicon_50.png
  src/View/Home/_header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: reviewed

#16 Feature/us02 visiteur home page navbar
  composer.json
  composer.lock
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/piece-50ans.png
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: corrections done, reviewed

#19 US11_visiteur_home_page-Réalisations
  src/View/Home/_realisations.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#20 S01 us18 visiteur footer informations
  composer.lock
  config/db.php.dist
  public/assets/css/footer.css
  public/assets/css/style.css
  src/View/_footer.html.twig
  src/View/layout.html.twig
Labels: reviewed

#22 Us05 visiteur home page evenements
  event.sql
  public/assets/css/homePage/events.css
  public/assets/css/style.css
  public/assets/images/01.png
  public/assets/images/02.jpg
  public/assets/images/03.jpg
  public/assets/images/04.jpg
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Model/EventManager.php
  src/View/Home/_events.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#27 Us19 visiteur footer redirect
  public/assets/css/legal.css
  public/assets/css/style.css
  src/Controller/LegalController.php
  src/View/Legal/privacyPolicy.html.twig
  src/View/_footer.html.twig
  src/View/layout.html.twig
Labels: reviewed

#26 Us12 visiteur home page réalisations
  public/assets/css/homePage/makings.css
  public/assets/css/style.css
  public/assets/images/assoc-emblem.png
  public/assets/images/piece-40ans.png
  public/assets/images/piece-50ans.png
  public/assets/images/piece-liberation.png
  src/View/Home/_makings.html.twig
  src/View/Home/_realisations.html.twig
  src/View/Home/index.html.twig
Labels: conflicts, corrections done, reviewed

#29 Us09 visiteur home page call to action
  public/assets/css/homePage/callToAction.css
  public/assets/css/style.css
  public/assets/images/president-ANC.jpeg
  src/View/Home/_callToAction.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/index.html.twig
Labels: corrections done, reviewed

#30 adjust responsive on card event
  public/assets/css/homePage/events.css
  src/View/Home/_events.html.twig
Labels: reviewed

#31 US08 Pages Description Home
  public/assets/css/homePage/homePageDescription.css
  public/assets/css/style.css
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#34 Correctif bug call to action
  public/assets/css/homePage/callToAction.css
  public/assets/css/homePage/header.css
  src/View/Home/_callToAction.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/index.html.twig
Labels: reviewed

#33 rectif responsive header section
  public/assets/css/homePage/header.css
  src/View/Home/_header.html.twig
Labels: reviewed

#35 Minor CSS modifications
  public/assets/css/footer.css
  public/assets/css/homePage/callToAction.css
  public/assets/css/homePage/makings.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  src/View/Home/_callToAction.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
Labels: reviewed

#36 Merge dev to Master
  composer.json
  composer.lock
  config/db.php.dist
  event.sql
  public/assets/css/contact.css
  public/assets/css/footer.css
  public/assets/css/homePage/callToAction.css
  public/assets/css/homePage/events.css
  public/assets/css/homePage/header.css
  public/assets/css/homePage/homePageDescription.css
  public/assets/css/homePage/makings.css
  public/assets/css/legal.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/01.png
  public/assets/images/02.jpg
  public/assets/images/03.jpg
  public/assets/images/04.jpg
  public/assets/images/anniversary_medal.png
  public/assets/images/assoc-emblem.png
  public/assets/images/bg_header.jpeg
  public/assets/images/favicon.png
  public/assets/images/favicon_50.png
  public/assets/images/piece-40ans.png
  public/assets/images/piece-50ans.png
  public/assets/images/piece-liberation.png
  public/assets/images/president-ANC.jpeg
  src/Controller/AbstractController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/Controller/LegalController.php
  src/Model/EventManager.php
  src/View/Contact/index.html.twig
  src/View/Home/_callToAction.html.twig
  src/View/Home/_events.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/_makings.html.twig
  src/View/Home/index.html.twig
  src/View/Legal/privacyPolicy.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: reviewed

#32 S02US17_visitor_contact-ButtonForm
  composer.lock
  public/assets/css/contact.css
  public/assets/css/style.css
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/ContactController.php
  src/Model/ContactManager.php
  src/View/Contact/index.html.twig
Labels: changes request, corrections done, reviewed

#75 S02US28_visitor_events-show_events
  public/assets/css/eventspage.css
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Event/index.html.twig
Labels: reviewed

#76 S02US20_visitor_collection-show_collection
  public/assets/css/collection/collection.css
  public/assets/css/style.css
  src/Controller/CollectionController.php
  src/View/Collection/index.html.twig
Labels: reviewed

#77 S02US29_visitor_events-zoom_picture
  src/View/Event/index.html.twig
Labels: reviewed

#78 S02US30_visitor_events-more_information
  src/View/Event/index.html.twig
Labels: reviewed

#70 S02US43_admin_home_page
  public/assets/css/admin/index.css
  src/Controller/AdminController.php
  src/View/Admin/index.html.twig
  src/View/_footer.html.twig
Labels: corrections done, reviewed

#82 S02US46_admin_message_page&dataBase
  public/assets/css/admin/index.css
  public/assets/css/admin/message.css
  public/assets/css/style.css
  src/Controller/AdminController.php
  src/Model/MessageManager.php
  src/View/Admin/index.html.twig
  src/View/Admin/message.html.twig
  src/View/_footer.html.twig
Labels: corrections done, reviewed

#83 S02US21_visitor_collection-show_picture_card
  public/assets/css/collection/collection.css
  public/assets/images/alfonsoXII-recto.jpg
  public/assets/images/alfonsoXII-verso.jpg
  public/assets/images/charlesIII-recto.jpg
  public/assets/images/charlesIII-verso.jpg
  public/assets/images/charlesVI-recto.jpg
  public/assets/images/charlesVI-verso.jpg
  public/assets/images/convention-recto.jpg
  public/assets/images/convention-verso.jpg
  public/assets/images/faustine-recto.jpg
  public/assets/images/faustine-verso.jpg
  public/assets/images/leucas-recto.jpg
  public/assets/images/leucas-verso.jpg
  public/assets/images/lindauer-recto.jpg
  public/assets/images/lindauer-verso.jpg
  public/assets/images/napoleonIII-recto.jpg
  public/assets/images/napoleonIII-verso.jpg
  public/assets/images/thoria-recto.jpg
  public/assets/images/thoria-verso.jpg
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
  src/View/Collection/index.html.twig
Labels: reviewed

#84 S02US40_visitor_club_life-main_page
  src/Controller/ClubLifeController.php
  src/View/ClubLife/index.html.twig
Labels: reviewed

#85 S02 us33 vistor exposition main
  event.sql
  public/assets/css/exihibition.css
  public/assets/images/01.jpg
  public/assets/images/exhibition/01.jpg
  public/assets/images/exhibition/02.jpg
  public/assets/images/exhibition/03.jpg
  public/assets/images/exhibition/04.jpg
  src/Controller/ExhibitionController.php
  src/Model/ExhibitionManager.php
  src/View/Exhibition/index.html.twig
Labels: reviewed

#86 S02US32_visitor_exposition_more_informations
  src/View/Exhibition/index.html.twig
Labels: reviewed

#87 S02US45_admin_event_page
  public/assets/css/admin/event.css
  public/assets/css/admin/index.css
  src/Controller/AdminController.php
  src/View/Admin/event.html.twig
  src/View/layout.html.twig
Labels: reviewed

#92 S02US23_visitor_collection-show_picture_zoom
  public/assets/css/collection/collection.css
  src/Model/CollectionManager.php
  src/View/Collection/index.html.twig
  src/View/Home/_makings.html.twig
  src/View/_navbar.html.twig
Labels: reviewed

#89 S02US41_visitor_club_life-description
  public/assets/images/clublife/bureau_ANC.jpg
  public/assets/images/clublife/presentation.jpg
  public/assets/images/clublife/visites.jpg
  src/View/ClubLife/index.html.twig
Labels: reviewed

#95 S02US48 admin exposition page
  src/Controller/AdminController.php
  src/View/Admin/exhibition.html.twig
  src/View/Admin/index.html.twig
Labels: reviewed

#96 S02 us34 visitor exposition more informations
  public/assets/css/exihibition.css
  public/assets/css/style.css
  src/View/Exhibition/index.html.twig
  src/View/_navbar.html.twig
Labels: reviewed

#97 S02US102_fixes_following_weekly_review
  public/assets/css/admin/index.css
  public/assets/css/collection/collection.css
  public/assets/css/style.css
  src/Controller/ClublifeController.php
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Event/index.html.twig
  src/View/Home/_events.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: reviewed

#98 S02US48_admin_exposition_list
  public/assets/css/admin/exhibition.css
  public/assets/css/admin/index.css
  src/Controller/AdminController.php
  src/Model/ExhibitionManager.php
  src/View/Admin/exhibition.html.twig
Labels: reviewed

#99 S02US47_admin_collection_list
  public/assets/css/admin/collection.css
  src/Controller/AdminController.php
  src/View/Admin/collection.html.twig
Labels: reviewed

#100 S02US104_fix_bg_color
  public/assets/css/collection/collection.css
  public/assets/css/style.css
Labels: reviewed

#102 S02US105_fix_link_and_CSS
  public/assets/css/clublife.css
  public/assets/css/contact.css
  public/assets/css/eventspage.css
  public/assets/images/events/02.jpg
  src/Model/EventManager.php
  src/View/Admin/message.html.twig
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/index.html.twig
  src/View/Exhibition/index.html.twig
Labels: reviewed

#119 S03US49_Admin-ClubLife_Page
  src/Controller/AdminController.php
  src/View/Admin/clublife.html.twig
  src/View/Admin/index.html.twig
Labels: reviewed

#122 S03US60_admin_exposition-edit_form
  src/Controller/ExhibitionController.php
  src/View/Admin/exhibition.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed

#116 S03US53_admin_collection_list-show
  public/assets/css/admin/editCoin.css
  public/assets/css/admin/index.css
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
  src/View/Admin/collection.html.twig
  src/View/Admin/edit.html.twig
Labels: changes request, corrections done, reviewed

#118 S03US36_retail_exhibition
  public/assets/css/exihibition.css
  src/View/Exhibition/index.html.twig
Labels: corrections done, reviewed

#123 S03US54_admin_collection_list_add-page
  src/Controller/CollectionController.php
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/collection.html.twig
  src/View/Exhibition/index.html.twig
Labels: corrections done, reviewed

#125 S03US53_admin_collection_list-files-control
  public/assets/css/homePage/header.css
  public/assets/images/collection/alfonsoXII-recto.jpg
  public/assets/images/collection/alfonsoXII-verso.jpg
  public/assets/images/collection/anniversary_medal.png
  public/assets/images/collection/assoc-emblem.png
  public/assets/images/collection/bg_header.jpeg
  public/assets/images/collection/charlesIII-recto.jpg
  public/assets/images/collection/charlesIII-verso.jpg
  public/assets/images/collection/charlesVI-recto.jpg
  public/assets/images/collection/charlesVI-verso.jpg
  public/assets/images/collection/convention-recto.jpg
  public/assets/images/collection/convention-verso.jpg
  public/assets/images/collection/faustine-recto.jpg
  public/assets/images/collection/faustine-verso.jpg
  public/assets/images/collection/leucas-recto.jpg
  public/assets/images/collection/leucas-verso.jpg
  public/assets/images/collection/lindauer-recto.jpg
  public/assets/images/collection/lindauer-verso.jpg
  public/assets/images/collection/napoleonIII-recto.jpg
  public/assets/images/collection/napoleonIII-verso.jpg
  public/assets/images/collection/piece-40ans.png
  public/assets/images/collection/piece-liberation.png
  public/assets/images/collection/president-ANC.jpg
  public/assets/images/collection/thoria-recto.jpg
  public/assets/images/collection/thoria-verso.jpg
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
  src/Verify/VerifyFileUpload.php
  src/View/Admin/collection.html.twig
  src/View/Admin/editCollection.html.twig
Labels: corrections done, reviewed

#126 Merge Dev to Master
  public/assets/css/admin/editCoin.css
  public/assets/css/admin/index.css
  public/assets/css/clublife.css
  public/assets/css/contact.css
  public/assets/css/eventspage.css
  public/assets/css/exihibition.css
  public/assets/css/homePage/header.css
  public/assets/images/collection/alfonsoXII-recto.jpg
  public/assets/images/collection/alfonsoXII-verso.jpg
  public/assets/images/collection/anniversary_medal.png
  public/assets/images/collection/assoc-emblem.png
  public/assets/images/collection/bg_header.jpeg
  public/assets/images/collection/charlesIII-recto.jpg
  public/assets/images/collection/charlesIII-verso.jpg
  public/assets/images/collection/charlesVI-recto.jpg
  public/assets/images/collection/charlesVI-verso.jpg
  public/assets/images/collection/convention-recto.jpg
  public/assets/images/collection/convention-verso.jpg
  public/assets/images/collection/faustine-recto.jpg
  public/assets/images/collection/faustine-verso.jpg
  public/assets/images/collection/leucas-recto.jpg
  public/assets/images/collection/leucas-verso.jpg
  public/assets/images/collection/lindauer-recto.jpg
  public/assets/images/collection/lindauer-verso.jpg
  public/assets/images/collection/napoleonIII-recto.jpg
  public/assets/images/collection/napoleonIII-verso.jpg
  public/assets/images/collection/piece-40ans.png
  public/assets/images/collection/piece-liberation.png
  public/assets/images/collection/president-ANC.jpg
  public/assets/images/collection/thoria-recto.jpg
  public/assets/images/collection/thoria-verso.jpg
  public/assets/images/events/02.jpg
  src/Controller/AdminController.php
  src/Controller/CollectionController.php
  src/Controller/ExhibitionController.php
  src/Model/CollectionManager.php
  src/Model/EventManager.php
  src/Verify/VerifyFileUpload.php
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/clublife.html.twig
  src/View/Admin/collection.html.twig
  src/View/Admin/editCollection.html.twig
  src/View/Admin/exhibition.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/message.html.twig
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/index.html.twig
  src/View/Exhibition/index.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed
