Repository WildCodeSchool/orleans-php-2003-project-anc, pull requests merged in 2020-05, with the labels that each got.

#128 S03US60_admin_exposition-Edit
  public/assets/images/collection/piece-50ans.png
  src/Controller/ExhibitionController.php
  src/Model/ExhibitionManager.php
  src/View/Admin/exhibition.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed

#129 S03US60_admin_exposition-edit_form
  src/Controller/ExhibitionController.php
  src/Model/ExhibitionManager.php
  src/View/Update/exhibition.html.twig
Labels: reviewed

#127 S04US53_update_to_bdd
  public/assets/css/admin/editCoin.css
  public/assets/css/style.css
  src/Controller/CollectionController.php
  src/Verify/VerifyFileUpload.php
  src/View/Admin/editCollection.html.twig
  src/View/layout.html.twig
Labels: corrections done, reviewed

#131 S04US53_admin_collection_add_coin-show
  src/Controller/CollectionController.php
  src/View/Admin/Add/addCollection.html.twig
Labels: reviewed

#132 S03US61_admin_exposition-add
  src/Controller/ExhibitionController.php
  src/Model/ExhibitionManager.php
  src/View/Admin/Add/exhibition.html.twig
  src/View/Admin/exhibition.html.twig
Labels: reviewed

#135 S04US62_ admin_exposition-Delete
  src/Controller/ExhibitionController.php
  src/Model/ExhibitionManager.php
  src/View/Admin/exhibition.html.twig
Labels: reviewed

#141 S04US106_fixes
  public/assets/css/collection/collection.css
  public/assets/images/clublife/president-ANC.jpg
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/_makings.html.twig
  src/View/_navbar.html.twig
Labels: reviewed

#145 S04US54_admin_collection_insert
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
Labels: reviewed

#142 S04US50_Admin-ClubLife_Edit
  public/assets/css/clublife.css
  public/assets/css/collection/collection.css
  public/assets/images/clublife/galette.jpg
  src/Controller/AdminController.php
  src/Controller/ClublifeController.php
  src/Controller/CollectionController.php
  src/Model/ClublifeManager.php
  src/Model/CollectionManager.php
  src/View/Admin/clublife.html.twig
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/_makings.html.twig
  src/View/_navbar.html.twig
Labels: corrections done, reviewed

#143 S04US107_Fix-Clublife-Responsive
  public/assets/css/clublife.css
  src/View/Clublife/index.html.twig
Labels: corrections done, reviewed

#150 S04US50_Admin-ClubLife_Edit
  public/assets/css/clublife.css
  public/assets/images/clublife/galette.jpg
  src/Controller/AdminController.php
  src/Controller/ClublifeController.php
  src/Model/ClublifeManager.php
  src/View/Admin/clublife.html.twig
  src/View/Clublife/index.html.twig
Labels: reviewed

#151 S04US109_fixes
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/clublife.html.twig
  src/View/Admin/collection.html.twig
  src/View/Admin/editCollection.html.twig
  src/View/Admin/event.html.twig
  src/View/Admin/exhibition.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/message.html.twig
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Event/index.html.twig
  src/View/Exhibition/index.html.twig
  src/View/Home/index.html.twig
  src/View/Legal/privacyPolicy.html.twig
Labels: reviewed

#152 S04US53_admin_collection_coin-delete
  public/assets/images/collection/5eb2a9cb394c31.70886138.png
  public/assets/images/collection/5eb2a9cb394c85.99825306.jpeg
  public/assets/images/collection/5eb2c8a7f37970.85619299.jpeg
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
  src/View/Admin/collection.html.twig
Labels: corrections done, reviewed

#154 S04US110_Fix
  public/assets/images/collection/5eb2a9cb394c31.70886138.png
  public/assets/images/collection/5eb2a9cb394c85.99825306.jpeg
  public/assets/images/collection/5eb2c8a7f37970.85619299.jpeg
  src/Controller/CollectionController.php
  src/View/Admin/Add/addCollection.html.twig
Labels: reviewed

#164 S05US66_admin_collection-origin-Show
  public/assets/css/admin/index.css
  public/assets/css/admin/option.css
  src/Controller/AdminController.php
  src/View/Admin/index.html.twig
  src/View/Admin/option.html.twig
Labels: reviewed

#165 S05US66_admin_collection_origin-add
  src/Controller/AdminController.php
  src/Model/CollectionManager.php
  src/Model/OptionManager.php
  src/View/Admin/option.html.twig
Labels: corrections done, reviewed

#168 S05US62 admin event add
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/Verify/VerifyDate.php
  src/View/Admin/Add/event.html.twig
  src/View/Admin/event.html.twig
Labels: reviewed

#169 S05US27_visitor_collection_sort-bar
  public/assets/css/collection/collection.css
  src/Controller/AdminController.php
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
  src/Services/Filter.php
  src/View/Admin/collection.html.twig
  src/View/Collection/index.html.twig
Labels: corrections done, reviewed

#170 S05US66_admin_collection_origin-modify
  src/Controller/AdminController.php
  src/Model/AbstractManager.php
  src/Model/OptionManager.php
  src/View/Admin/option.html.twig
Labels: reviewed

#172 S05US64-Admin-Event-Update
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Admin/editEvent.html.twig
  src/View/Admin/event.html.twig
Labels: changes request, corrections done, reviewed

#173 S05US67_Subject_Contact-CRUD
  src/Controller/AdminController.php
  src/Model/CollectionManager.php
  src/Model/OptionManager.php
  src/View/Admin/option.html.twig
Labels: corrections done, reviewed

#175 S05US68_admin_collection_material-Update-Select-Add
  src/Controller/AdminController.php
  src/View/Admin/option.html.twig
Labels: corrections done, reviewed

#177 S05US63-admin-event-delete
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Admin/event.html.twig
  src/View/Event/index.html.twig
Labels: reviewed

#178 S05US111-Fix-Image_Transparency
  public/assets/images/collection/alfonsoXII-recto.jpg
  public/assets/images/collection/alfonsoXII-verso.jpg
  public/assets/images/collection/charlesIII-recto.jpg
  public/assets/images/collection/charlesIII-verso.jpg
  public/assets/images/collection/charlesVI-recto.jpg
  public/assets/images/collection/charlesVI-verso.jpg
  public/assets/images/collection/convention-recto.jpg
  public/assets/images/collection/convention-verso.jpg
  public/assets/images/collection/faustine-recto.jpg
  public/assets/images/collection/faustine-verso.jpg
  public/assets/images/collection/leucas-recto.jpg
  public/assets/images/collection/leucas-verso.jpg
  public/assets/images/collection/lindauer-recto.jpg
  public/assets/images/collection/lindauer-verso.jpg
  public/assets/images/collection/napoleonIII-recto.jpg
  public/assets/images/collection/napoleonIII-verso.jpg
  public/assets/images/collection/thoria-recto.jpg
  public/assets/images/collection/thoria-verso.jpg
Labels: reviewed

#181 S05US70_event_index_custom-number-on-card
  src/Controller/AdminController.php
  src/Model/AdminManager.php
  src/View/Admin/index.html.twig
Labels: reviewed

#183 S05US71_added_subject_in_selectOption
  src/Controller/ContactController.php
  src/Model/ContactManager.php
  src/View/Contact/index.html.twig
Labels: reviewed

#186 S05US72_collection_visiteurs-cards
  public/assets/css/collection/collection.css
  src/View/Collection/index.html.twig
Labels: reviewed

#194 FIX_List-emails-admin#193
  public/assets/css/admin/message.css
  public/assets/css/style.css
  src/View/Admin/message.html.twig
Labels: reviewed

#185 S05US69-Dark_Mode
  public/assets/css/admin/collection.css
  public/assets/css/admin/editCoin.css
  public/assets/css/admin/exhibition.css
  public/assets/css/admin/message.css
  public/assets/css/admin/option.css
  public/assets/css/clublife.css
  public/assets/css/collection/collection.css
  public/assets/css/contact.css
  public/assets/css/exihibition.css
  public/assets/css/homePage/callToAction.css
  public/assets/css/style.css
Labels: conflicts

#196 Dev to master
  public/assets/css/admin/collection.css
  public/assets/css/admin/editCoin.css
  public/assets/css/admin/exhibition.css
  public/assets/css/admin/index.css
  public/assets/css/admin/message.css
  public/assets/css/admin/option.css
  public/assets/css/clublife.css
  public/assets/css/collection/collection.css
  public/assets/css/contact.css
  public/assets/css/exihibition.css
  public/assets/css/homePage/callToAction.css
  public/assets/css/style.css
  public/assets/images/collection/5eb2a9cb394c31.70886138.png
  public/assets/images/collection/5eb2a9cb394c85.99825306.jpeg
  public/assets/images/collection/5eb2c8a7f37970.85619299.jpeg
  public/assets/images/collection/alfonsoXII-recto.jpg
  public/assets/images/collection/alfonsoXII-verso.jpg
  public/assets/images/collection/charlesIII-recto.jpg
  public/assets/images/collection/charlesIII-verso.jpg
  public/assets/images/collection/charlesVI-recto.jpg
  public/assets/images/collection/charlesVI-verso.jpg
  public/assets/images/collection/convention-recto.jpg
  public/assets/images/collection/convention-verso.jpg
  public/assets/images/collection/faustine-recto.jpg
  public/assets/images/collection/faustine-verso.jpg
  public/assets/images/collection/leucas-recto.jpg
  public/assets/images/collection/leucas-verso.jpg
  public/assets/images/collection/lindauer-recto.jpg
  public/assets/images/collection/lindauer-verso.jpg
  public/assets/images/collection/napoleonIII-recto.jpg
  public/assets/images/collection/napoleonIII-verso.jpg
  public/assets/images/collection/thoria-recto.jpg
  public/assets/images/collection/thoria-verso.jpg
  src/Controller/AdminController.php
  src/Controller/CollectionController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Model/AbstractManager.php
  src/Model/AdminManager.php
  src/Model/CollectionManager.php
  src/Model/ContactManager.php
  src/Model/EventManager.php
  src/Model/OptionManager.php
  src/Services/Filter.php
  src/Verify/VerifyDate.php
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/Add/event.html.twig
  src/View/Admin/collection.html.twig
  src/View/Admin/editEvent.html.twig
  src/View/Admin/event.html.twig
  src/View/Admin/index.html.twig
  src/View/Admin/message.html.twig
  src/View/Admin/option.html.twig
  src/View/Collection/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/index.html.twig
Labels: reviewed

#199 Fix contact guest #199
  public/assets/css/contact.css
  src/Controller/ContactController.php
  src/View/Contact/index.html.twig
Labels: corrections done, reviewed

#200 Fix-Admin-Clublife_issue, issue #190
  src/View/Admin/clublife.html.twig
Labels: reviewed

#206 Fix-spelling-correction-exhibition-part-admin#197
  src/View/Admin/exhibition.html.twig
Labels: reviewed

#201 Fix-Event-Cards_Default_Description, issue #198
  src/View/Event/index.html.twig
Labels: reviewed

#204 Fix-Dark_Mode-Admin-Option, issue #202
  public/assets/css/admin/option.css
Labels: reviewed

#210 FIX correctif error W3C
  public/assets/css/style.css
  src/View/Exhibition/index.html.twig
  src/View/Home/_callToAction.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/_footer.html.twig
Labels: reviewed

#212 Fix-EventController-ShowAllEvent
  src/Controller/AdminController.php
  src/Controller/EventController.php
  src/Model/EventManager.php
Labels: reviewed

#213 Fix file control admin collection
  src/Controller/CollectionController.php
  src/Controller/ExhibitionController.php
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/Add/exhibition.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed

#214 Fix center card admin
  src/View/Admin/collection.html.twig
Labels: reviewed

#215 Fix form summernote admin collection
  src/View/Admin/Add/addCollection.html.twig
Labels: reviewed

#218 Fix_contact_checkbox_not_displaying
  public/assets/css/collection/collection.css
Labels: reviewed

#219 Fix_summernote_form_exhibition_admin
  public/assets/css/admin/exhibition.css
  src/View/Admin/Add/exhibition.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed

#220 Fix_exhibition_title_not_displaying
  src/View/Admin/exhibition.html.twig
  src/View/Exhibition/index.html.twig
Labels: reviewed

#221 Fix_selected_checkbox_collection
  src/View/Admin/collection.html.twig
  src/View/Collection/index.html.twig
Labels: reviewed

#223 standardization of event pages
  public/assets/css/style.css
  src/View/Admin/Add/event.html.twig
  src/View/Admin/editEvent.html.twig
  src/View/Admin/event.html.twig
Labels: reviewed

#226 Fix_left_and_right_collection_section_margin
  src/View/Collection/index.html.twig
Labels: reviewed

#225 Fix_centered_exhibition_modal_visitor_page
  src/View/Exhibition/index.html.twig
Labels: corrections done, reviewed

#227 FIX page club life
  src/View/Admin/clublife.html.twig
  src/View/layout.html.twig
Labels: reviewed

#229 fix-home#228
  public/assets/css/homePage/events.css
  src/View/Home/_events.html.twig
Labels: reviewed

#231 Fix-Visitor-Event-Responsive, issue #230
  public/assets/css/eventspage.css
Labels: reviewed

#232 Fix_display_admin_collection
  public/assets/css/admin/collection.css
  src/View/Admin/collection.html.twig
Labels: reviewed

#233 FIX navbar
  src/View/_navbar.html.twig
Labels: reviewed

#235 Fix-Visitor-Contact-Placeholder, issue #234
  src/View/Contact/index.html.twig
Labels: reviewed

#236 Fix_reset_button_missing_collection
  src/View/Admin/collection.html.twig
  src/View/Collection/index.html.twig
Labels: reviewed

#237 Fix_attend_button_missing_event
  src/View/Event/index.html.twig
Labels: reviewed

#239 Fix-Hover-Color-Button, issue #238
  public/assets/css/style.css
Labels: reviewed

#240 Fix_Add_coin_not_working
  src/Controller/CollectionController.php
Labels: reviewed

#242 Dark Mode, Fix Modal Color, issue #241
  public/assets/css/exihibition.css
Labels: reviewed

#243 FIX Rectif bug home
  public/assets/css/footer.css
  public/assets/css/homePage/events.css
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/_makings.html.twig
  src/View/layout.html.twig
Labels: reviewed

#244 Fix_add_coin_form_not_retaining_information
  src/View/Admin/Add/addCollection.html.twig
Labels: reviewed

#246 Fix_admin_titles_consistency
  src/View/Admin/Add/event.html.twig
  src/View/Admin/Add/exhibition.html.twig
  src/View/Admin/collection.html.twig
  src/View/Admin/editCollection.html.twig
  src/View/Admin/editEvent.html.twig
  src/View/Admin/event.html.twig
  src/View/Admin/exhibition.html.twig
  src/View/Update/exhibition.html.twig
Labels: reviewed

#248 Fix-mentions-legales#247
  src/View/Legal/privacyPolicy.html.twig
  src/View/_footer.html.twig
Labels: reviewed

#250 Fix Clublife Margin, issue #249
  public/assets/css/clublife.css
  src/View/Clublife/index.html.twig
Labels: reviewed

#245 FIX confirm delete
  public/assets/js/app.js
  src/View/Admin/collection.html.twig
  src/View/Admin/event.html.twig
  src/View/Admin/exhibition.html.twig
  src/View/Admin/message.html.twig
  src/View/Admin/option.html.twig
  src/View/layout.html.twig
Labels: changes request, conflicts, corrections done, reviewed

#251 Fix_raw_data_form
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Exhibition/index.html.twig
Labels: corrections done, reviewed

#252 Fix_error_file_upload
  src/Controller/CollectionController.php
  src/Model/CollectionManager.php
Labels: reviewed

#253 Fix_cancel_button_working
  src/View/Collection/index.html.twig
Labels: reviewed

#254 Fix adapt chrom
  public/assets/css/collection/collection.css
  src/View/Collection/index.html.twig
Labels: reviewed

#255 remove dump in file
  src/View/Admin/Add/addCollection.html.twig
Labels: reviewed

#256 Merge final
  public/assets/css/admin/collection.css
  public/assets/css/admin/exhibition.css
  public/assets/css/admin/option.css
  public/assets/css/clublife.css
  public/assets/css/collection/collection.css
  public/assets/css/contact.css
  public/assets/css/eventspage.css
  public/assets/css/exihibition.css
  public/assets/css/footer.css
  public/assets/css/homePage/events.css
  public/assets/css/style.css
  public/assets/js/app.js
  src/Controller/AdminController.php
  src/Controller/CollectionController.php
  src/Controller/ContactController.php
  src/Controller/EventController.php
  src/Controller/ExhibitionController.php
  src/Model/CollectionManager.php
  src/Model/EventManager.php
  src/View/Admin/Add/addCollection.html.twig
  src/View/Admin/Add/event.html.twig
  src/View/Admin/Add/exhibition.html.twig
  src/View/Admin/clublife.html.twig
  src/View/Admin/collection.html.twig
  src/View/Admin/editCollection.html.twig
  src/View/Admin/editEvent.html.twig
  src/View/Admin/event.html.twig
  src/View/Admin/exhibition.html.twig
  src/View/Admin/message.html.twig
  src/View/Admin/option.html.twig
  src/View/Clublife/index.html.twig
  src/View/Collection/index.html.twig
  src/View/Contact/index.html.twig
  src/View/Event/index.html.twig
  src/View/Exhibition/index.html.twig
  src/View/Home/_callToAction.html.twig
  src/View/Home/_events.html.twig
  src/View/Home/_header.html.twig
  src/View/Home/_homePageDescription.html.twig
  src/View/Home/_makings.html.twig
  src/View/Legal/privacyPolicy.html.twig
  src/View/Update/exhibition.html.twig
  src/View/_footer.html.twig
  src/View/_navbar.html.twig
  src/View/layout.html.twig
Labels: reviewed

#257 fix-exhibition-img
  public/assets/css/collection/collection.css
Labels: reviewed

#258 resolve bug contact
  src/Controller/ContactController.php
Labels: reviewed

#259 Merge final
  public/assets/css/collection/collection.css
  src/Controller/ContactController.php
Labels: reviewed
